/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Historial;

/**
 *
 * @author Ximena
 */
public class TramiteHistorial extends javax.swing.JPanel {

    /**
     * Creates new form TramiteHistorial
     */
    public TramiteHistorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAnioNacimiento = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCURP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAnioNacimiento.setBackground(new java.awt.Color(217, 217, 217));
        add(txtAnioNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 160, 30));

        txtNombre.setBackground(new java.awt.Color(217, 217, 217));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 160, 30));

        txtCURP.setBackground(new java.awt.Color(217, 217, 217));
        add(txtCURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ximena\\Documents\\GitHub\\BD-Proyecto-2\\Proyecto2\\AgenciaPresentacion\\src\\main\\resources\\Imagenes\\TramiteHistorialCap.PNG")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 130, 30));

        botonAceptar.setText("jButton1");
        add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 130, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAnioNacimiento;
    private javax.swing.JTextField txtCURP;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
