/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Placas;

/**
 *
 * @author Ximena
 */
public class PlacaGenerada extends javax.swing.JFrame {

    /**
     * Creates new form PlacaGenerada
     */
    public PlacaGenerada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrecio = new javax.swing.JTextField();
        txtPlacasNuevas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonRegresarMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrecio.setEditable(false);
        txtPrecio.setBackground(new java.awt.Color(217, 217, 217));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 200, 40));

        txtPlacasNuevas.setEditable(false);
        txtPlacasNuevas.setBackground(new java.awt.Color(217, 217, 217));
        getContentPane().add(txtPlacasNuevas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ximena\\Documents\\GitHub\\BD-Proyecto-2\\Proyecto2\\AgenciaPresentacion\\src\\main\\resources\\Imagenes\\PlacasGeneradasCap.PNG")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        botonRegresarMenu.setText("jButton1");
        getContentPane().add(botonRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 304, 210, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPlacasNuevas;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
