/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Placas;

/**
 *
 * @author Ximena
 */
public class TramiteAutoUsado extends javax.swing.JFrame {

    /**
     * Creates new form TramiteAutoUsado
     */
    public TramiteAutoUsado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPlacasAntiguas = new javax.swing.JTextField();
        txtLicencia = new javax.swing.JTextField();
        jajajja = new javax.swing.JLabel();
        botonIngresar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtPlacasAntiguas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 250, 30));
        getContentPane().add(txtLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 250, -1));

        jajajja.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ximena\\Documents\\GitHub\\BD-Proyecto-2\\Proyecto2\\AgenciaPresentacion\\src\\main\\resources\\Imagenes\\TramiteAutoUsadoCap.PNG")); // NOI18N
        getContentPane().add(jajajja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 310));
        getContentPane().add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 130, 30));

        botonRegresar.setText("jButton1");
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jajajja;
    private javax.swing.JTextField txtLicencia;
    private javax.swing.JTextField txtPlacasAntiguas;
    // End of variables declaration//GEN-END:variables
}
