/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Placas;

/**
 *
 * @author Ximena
 */
public class TramiteAutoNuevo extends javax.swing.JFrame {

    /**
     * Creates new form TramiteAutoNuevo
     */
    public TramiteAutoNuevo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLineaAuto = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtNumSerie = new javax.swing.JTextField();
        txtLicencia = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtModeloAuto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        txtModeloAuto1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLineaAuto.setBackground(new java.awt.Color(130, 130, 130));
        getContentPane().add(txtLineaAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 210, 30));

        txtMarca.setBackground(new java.awt.Color(130, 130, 130));
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, 30));

        txtNumSerie.setBackground(new java.awt.Color(130, 130, 130));
        getContentPane().add(txtNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, 210, 30));

        txtLicencia.setBackground(new java.awt.Color(130, 130, 130));
        getContentPane().add(txtLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 224, 210, 30));

        txtColor.setBackground(new java.awt.Color(130, 130, 130));
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 210, 30));

        txtModeloAuto.setBackground(new java.awt.Color(130, 130, 130));
        getContentPane().add(txtModeloAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 96, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ximena\\Documents\\GitHub\\BD-Proyecto-2\\Proyecto2\\AgenciaPresentacion\\src\\main\\resources\\Imagenes\\TramiteAutoNuevoCap.PNG")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        botonAceptar.setText("jButton1");
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 140, 30));

        botonRegresar.setText("jButton1");
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 130, 30));

        txtModeloAuto1.setBackground(new java.awt.Color(130, 130, 130));
        getContentPane().add(txtModeloAuto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 96, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtLicencia;
    private javax.swing.JTextField txtLineaAuto;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModeloAuto;
    private javax.swing.JTextField txtModeloAuto1;
    private javax.swing.JTextField txtNumSerie;
    // End of variables declaration//GEN-END:variables
}
