/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Placas;

import DTOs.AutomovilDTO;
import GUI.Ventana;
import negocio.RegistroPlacasBO;

/**
 *
 * @author yohan
 */
public class TramiteGenerarPlacas extends javax.swing.JPanel {
    private Ventana ventana;
    private AutomovilDTO auto;
    /**
     * Creates new form TramiteGenerarPlacas
     */
    public TramiteGenerarPlacas() {
        initComponents();
    }
     public TramiteGenerarPlacas(Ventana ventana,AutomovilDTO auto) {
        this.ventana = ventana;
        this.auto = auto;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
