/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Placas;

import DTOs.AutomovilDTO;
import DTOs.PlacasDTO;
import Excepciones.persistenciaException;
import GUI.Ventana;
import Inegocio.IRegistroLicenciaBO;
import Inegocio.IRegistroPlacasBO;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.RegistroLicenciaBO;
import negocio.RegistroPlacasBO;

/**
 *
 * @author USER
 */
public class TramiteAutoNuevo extends javax.swing.JPanel {

    private Ventana ventana;
    private IRegistroPlacasBO rp;

    /**
     * Creates new form TramiteAutoNuevo1
     */
    public TramiteAutoNuevo() {
        initComponents();
    }

    public TramiteAutoNuevo(Ventana ventana) {
        this.ventana = ventana;
        this.rp = new RegistroPlacasBO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLineaAuto = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtNumSerie = new javax.swing.JTextField();
        txtLicencia = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtModeloAuto = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TramiteAutoNuevoCap.PNG"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 340));

        txtLineaAuto.setBackground(new java.awt.Color(130, 130, 130));
        txtLineaAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLineaAutoActionPerformed(evt);
            }
        });
        add(txtLineaAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 210, 30));

        txtMarca.setBackground(new java.awt.Color(130, 130, 130));
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, 30));

        txtNumSerie.setBackground(new java.awt.Color(130, 130, 130));
        txtNumSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumSerieActionPerformed(evt);
            }
        });
        add(txtNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, 30));

        txtLicencia.setBackground(new java.awt.Color(130, 130, 130));
        txtLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenciaActionPerformed(evt);
            }
        });
        add(txtLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 210, 30));

        txtColor.setBackground(new java.awt.Color(130, 130, 130));
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 210, 30));

        txtModeloAuto.setBackground(new java.awt.Color(130, 130, 130));
        txtModeloAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloAutoActionPerformed(evt);
            }
        });
        add(txtModeloAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 210, 30));

        botonAceptar.setBorderPainted(false);
        botonAceptar.setContentAreaFilled(false);
        botonAceptar.setFocusPainted(false);
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 140, 30));

        botonRegresar.setBorderPainted(false);
        botonRegresar.setContentAreaFilled(false);
        botonRegresar.setFocusPainted(false);
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        ventana.cambiarVistaPlaca();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        String Numero_Serie = txtNumSerie.getText();
        String Modelo = txtModeloAuto.getText();
        String linea = txtLineaAuto.getText();
        String licencia = txtLicencia.getText();
        String color = txtColor.getText();
        String marca = txtMarca.getText();
        IRegistroLicenciaBO rl=new RegistroLicenciaBO();
        AutomovilDTO auto = new AutomovilDTO(Numero_Serie, Modelo, linea, marca, color, rl.regresarLicencias(licencia));
        Calendar fecha_emision,fecha_recepcion;
        fecha_emision=Calendar.getInstance();
        fecha_recepcion=Calendar.getInstance();
        PlacasDTO placa = new PlacasDTO("Nuevo", "Activa", fecha_emision, fecha_recepcion, 1500.f);
        try {
            String numeroPlaca=rp.RegistrarPlacasNuevas(placa, auto);
            placa.setNumero(numeroPlaca);
        } catch (persistenciaException ex) {
            Logger.getLogger(TramiteAutoNuevo.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventana.cambiarVistaTramiteGenerar(auto,"nuevo");
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void txtLineaAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLineaAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLineaAutoActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtNumSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumSerieActionPerformed

    private void txtLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenciaActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtModeloAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloAutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtLicencia;
    private javax.swing.JTextField txtLineaAuto;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModeloAuto;
    private javax.swing.JTextField txtNumSerie;
    // End of variables declaration//GEN-END:variables
}
