/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Placas;

import GUI.Ventana;
import Inegocio.IRegistroPlacasBO;
import negocio.RegistroPlacasBO;

/**
 *
 * @author USER
 */
public class TramitePlacas extends javax.swing.JPanel {

   
    private Ventana ventana;
    /**
     * Creates new form TramitePlacas
     */
    public TramitePlacas() {
        initComponents();
    }
    
    public TramitePlacas(Ventana ventana) {
        this.ventana = ventana;
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AutoNuevoButton = new javax.swing.JButton();
        AutoUsadoButton = new javax.swing.JButton();
        RegresarButton = new javax.swing.JButton();

        AutoNuevoButton.setText("Auto Nuevo");
        AutoNuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoNuevoButtonActionPerformed(evt);
            }
        });

        AutoUsadoButton.setText("Auto Usado");
        AutoUsadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoUsadoButtonActionPerformed(evt);
            }
        });

        RegresarButton.setText("Regresar");
        RegresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegresarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AutoNuevoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(AutoUsadoButton)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AutoNuevoButton)
                    .addComponent(AutoUsadoButton))
                .addGap(64, 64, 64)
                .addComponent(RegresarButton)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AutoNuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoNuevoButtonActionPerformed
        // TODO add your handling code here:
        ventana.cambiarVistaTramiteAutoNuevo();
        
        
    }//GEN-LAST:event_AutoNuevoButtonActionPerformed

    private void AutoUsadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoUsadoButtonActionPerformed
        // TODO add your handling code here:
        ventana.cambiarVistaTramiteAutoUsado();
    }//GEN-LAST:event_AutoUsadoButtonActionPerformed

    private void RegresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButtonActionPerformed
        // TODO add your handling code here:
        ventana.cambiarVistaMenu();
    }//GEN-LAST:event_RegresarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AutoNuevoButton;
    private javax.swing.JButton AutoUsadoButton;
    private javax.swing.JButton RegresarButton;
    // End of variables declaration//GEN-END:variables
}
