/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Placas;

import GUI.ControladorVentana;
import Inegocio.IRegistroPlacasBO;
import negocio.RegistroPlacasBO;

/**
 *
 * @author Yohan Gabriel Melendrez Leal - 244907
 * @author Jesus Francisco Tapia Maldonado - 245136
 * @author Ximena Oliva Andrade - 247563
 */
public class TramitePlacas extends javax.swing.JPanel {

   
    private ControladorVentana ventana;
    /**
     * Creates new form TramitePlacas
     */
    public TramitePlacas() {
        initComponents();
    }
    
    public TramitePlacas(ControladorVentana ventana) {
        this.ventana = ventana;
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AutoNuevoButton = new javax.swing.JButton();
        AutoUsadoButton = new javax.swing.JButton();
        RegresarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AutoNuevoButton.setBorderPainted(false);
        AutoNuevoButton.setContentAreaFilled(false);
        AutoNuevoButton.setFocusPainted(false);
        AutoNuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoNuevoButtonActionPerformed(evt);
            }
        });
        add(AutoNuevoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 180, 50));

        AutoUsadoButton.setBorderPainted(false);
        AutoUsadoButton.setContentAreaFilled(false);
        AutoUsadoButton.setFocusPainted(false);
        AutoUsadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoUsadoButtonActionPerformed(evt);
            }
        });
        add(AutoUsadoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 180, 50));

        RegresarButton.setBorderPainted(false);
        RegresarButton.setContentAreaFilled(false);
        RegresarButton.setFocusPainted(false);
        RegresarButton.setFocusable(false);
        RegresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButtonActionPerformed(evt);
            }
        });
        add(RegresarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SeleccionDeAutoCap.PNG"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void AutoNuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoNuevoButtonActionPerformed
        // TODO add your handling code here:
        ventana.cambiarVistaTramiteAutoNuevo();
        
        
    }//GEN-LAST:event_AutoNuevoButtonActionPerformed

    private void AutoUsadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoUsadoButtonActionPerformed
        // TODO add your handling code here:
        ventana.cambiarVistaTramiteAutoUsado();
    }//GEN-LAST:event_AutoUsadoButtonActionPerformed

    private void RegresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButtonActionPerformed
        // TODO add your handling code here:
        ventana.cambiarVistaMenu();
    }//GEN-LAST:event_RegresarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AutoNuevoButton;
    private javax.swing.JButton AutoUsadoButton;
    private javax.swing.JButton RegresarButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
