package GUI;

import GUI.ControladorVentana;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Yohan Gabriel Melendrez Leal - 244907
 * @author Jesus Francisco Tapia Maldonado - 245136
 * @author Ximena Oliva Andrade - 247563
 */
public class Menu extends javax.swing.JPanel {

    private ControladorVentana ventana;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    public Menu(ControladorVentana ventana) {
        this.ventana = ventana;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        BotonPlacas = new javax.swing.JButton();
        BotonLicencia = new javax.swing.JButton();
        BotonReportes = new javax.swing.JButton();
        BotonConsultas = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InicioCap.PNG"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 390));

        BotonPlacas.setContentAreaFilled(false);
        BotonPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPlacasActionPerformed(evt);
            }
        });
        add(BotonPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 130, 40));

        BotonLicencia.setContentAreaFilled(false);
        BotonLicencia.setFocusPainted(false);
        BotonLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLicenciaActionPerformed(evt);
            }
        });
        add(BotonLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 130, 30));

        BotonReportes.setContentAreaFilled(false);
        BotonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReportesActionPerformed(evt);
            }
        });
        add(BotonReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 140, 40));

        BotonConsultas.setContentAreaFilled(false);
        BotonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultasActionPerformed(evt);
            }
        });
        add(BotonConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLicenciaActionPerformed
        ventana.cambiarVistaLicencia();
    }//GEN-LAST:event_BotonLicenciaActionPerformed

    private void BotonPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPlacasActionPerformed
        // TODO add your handling code here:
        ventana.cambiarVistaPlaca();
    }//GEN-LAST:event_BotonPlacasActionPerformed

    private void BotonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReportesActionPerformed
ventana.cambiarVistaTramiteReporte();
    }//GEN-LAST:event_BotonReportesActionPerformed

    private void BotonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultasActionPerformed
        ventana.cambiarVistaConsulta();
    }//GEN-LAST:event_BotonConsultasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConsultas;
    private javax.swing.JButton BotonLicencia;
    private javax.swing.JButton BotonPlacas;
    private javax.swing.JButton BotonReportes;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
