/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Ximena
 */
public class TramitePlacas extends javax.swing.JFrame {

    /**
     * Creates new form TramitePlacas
     */
    public TramitePlacas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonAutoUsado = new javax.swing.JButton();
        botonAutoNuevo = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ximena\\Documents\\GitHub\\BD-Proyecto-2\\Proyecto2\\AgenciaPresentacion\\src\\main\\resources\\Imagenes\\SeleccionDeAutoCap.PNG")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 355));

        botonAutoUsado.setText("jButton1");
        getContentPane().add(botonAutoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 170, 30));

        botonAutoNuevo.setText("jButton1");
        getContentPane().add(botonAutoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 170, 30));
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAutoNuevo;
    private javax.swing.JButton botonAutoUsado;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
