/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Ximena
 */
public class VigenciaLicencia extends javax.swing.JFrame {

    /**
     * Creates new form VigenciaLicencia
     */
    public VigenciaLicencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        CheckBox3anios = new javax.swing.JCheckBox();
        CheckBox1anio1 = new javax.swing.JCheckBox();
        CheckBox2anios = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        BotonAceptar = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CheckBox3anios.setBackground(new java.awt.Color(217, 217, 217));
        CheckBox3anios.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        CheckBox3anios.setForeground(new java.awt.Color(0, 0, 0));
        CheckBox3anios.setText("3 Años");
        getContentPane().add(CheckBox3anios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 150, 30));

        CheckBox1anio1.setBackground(new java.awt.Color(217, 217, 217));
        CheckBox1anio1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        CheckBox1anio1.setForeground(new java.awt.Color(0, 0, 0));
        CheckBox1anio1.setText("1 Año");
        getContentPane().add(CheckBox1anio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 30));

        CheckBox2anios.setBackground(new java.awt.Color(217, 217, 217));
        CheckBox2anios.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        CheckBox2anios.setForeground(new java.awt.Color(0, 0, 0));
        CheckBox2anios.setText("2 Años");
        getContentPane().add(CheckBox2anios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ximena\\Documents\\GitHub\\BD-Proyecto-2\\Proyecto2\\AgenciaPresentacion\\src\\main\\resources\\Imagenes\\TablaVigenciaCap.PNG")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(BotonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 140, 40));
        getContentPane().add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JCheckBox CheckBox1anio1;
    private javax.swing.JCheckBox CheckBox2anios;
    private javax.swing.JCheckBox CheckBox3anios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
