/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Licencia;

import DTOs.LicenciaDTO;
import Excepciones.persistenciaException;
import GUI.ControladorVentana;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.RegistroLicenciaBO;

/**
 *
 * @author Yohan Gabriel Melendrez Leal - 244907
 * @author Jesus Francisco Tapia Maldonado - 245136
 * @author Ximena Oliva Andrade - 247563
 */
public class LicenciaGenerada extends javax.swing.JPanel {

    private ControladorVentana ventana;
    private RegistroLicenciaBO rlb;

    /**
     * Creates new form LicenciaGenerada1
     */
    public LicenciaGenerada() {
        initComponents();
    }

    public LicenciaGenerada(ControladorVentana ventana, LicenciaDTO licencia) {
        this.ventana = ventana;
        this.rlb = new RegistroLicenciaBO();
        initComponents();
        txtLicencia.setText(licencia.getNumeroLicencia());
        txtLicencia.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLicencia = new javax.swing.JTextField();
        botonRegresarMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLicencia.setEditable(false);
        txtLicencia.setBackground(new java.awt.Color(217, 217, 217));
        txtLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenciaActionPerformed(evt);
            }
        });
        add(txtLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 230, 50));

        botonRegresarMenu.setBorderPainted(false);
        botonRegresarMenu.setContentAreaFilled(false);
        botonRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarMenuActionPerformed(evt);
            }
        });
        add(botonRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 240, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LicenciaGeneradaCap.PNG"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarMenuActionPerformed
        ventana.cambiarVistaMenu();
    }//GEN-LAST:event_botonRegresarMenuActionPerformed

    private void txtLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenciaActionPerformed

    }//GEN-LAST:event_txtLicenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtLicencia;
    // End of variables declaration//GEN-END:variables
}
