/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Licencia;

import DTOs.LicenciaDTO;
import Excepciones.persistenciaException;
import GUI.Ventana;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.RegistroLicenciaBO;

/**
 *
 * @author yohan
 */
public class LicenciaGenerada extends javax.swing.JPanel {

    private Ventana ventana;
    private RegistroLicenciaBO rlb;

    /**
     * Creates new form LicenciaGenerada1
     */
    public LicenciaGenerada() {
        initComponents();
    }

    public LicenciaGenerada(Ventana ventana, LicenciaDTO licencia) {
        this.ventana = ventana;
        this.rlb = new RegistroLicenciaBO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegresarMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRegresarMenu.setBorderPainted(false);
        botonRegresarMenu.setContentAreaFilled(false);
        botonRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarMenuActionPerformed(evt);
            }
        });
        add(botonRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 270, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/generada.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarMenuActionPerformed
        ventana.cambiarVistaMenu();
    }//GEN-LAST:event_botonRegresarMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresarMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
