/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Licencia;

import DTOs.LicenciaDTO;
import Encriptador.Encriptador;
import Entidades.Licencia;
import Entidades.Persona;
import Excepciones.persistenciaException;
import GUI.ControladorVentana;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.RegistroLicenciaBO;

/**
 *
 * @author Yohan Gabriel Melendrez Leal - 244907
 * @author Jesus Francisco Tapia Maldonado - 245136
 * @author Ximena Oliva Andrade - 247563
 */
public class TramiteLicenciaMenu extends javax.swing.JPanel {

    private ControladorVentana ventana;
    private RegistroLicenciaBO rlb;
    private boolean datosMostrados = false;

    /**
     * Creates new form Licencia
     */
    public TramiteLicenciaMenu() {
        initComponents();
    }

    public TramiteLicenciaMenu(ControladorVentana ventana) {
        this.ventana = ventana;
        this.rlb = new RegistroLicenciaBO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFecha_nacimiento = new javax.swing.JTextField();
        txtIngreseRFC = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        BotonIngresar = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFecha_nacimiento.setEditable(false);
        txtFecha_nacimiento.setBackground(new java.awt.Color(217, 217, 217));
        txtFecha_nacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFecha_nacimientoActionPerformed(evt);
            }
        });
        add(txtFecha_nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 240, 50));

        txtIngreseRFC.setBackground(new java.awt.Color(217, 217, 217));
        txtIngreseRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngreseRFCActionPerformed(evt);
            }
        });
        add(txtIngreseRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 240, 50));

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(217, 217, 217));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 250, 50));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(217, 217, 217));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 250, 50));

        BotonIngresar.setBorderPainted(false);
        BotonIngresar.setContentAreaFilled(false);
        BotonIngresar.setFocusPainted(false);
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 150, 40));

        BotonRegresar.setBorderPainted(false);
        BotonRegresar.setContentAreaFilled(false);
        BotonRegresar.setFocusPainted(false);
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });
        add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tramite 2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
        if (txtIngreseRFC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el rfc antes");
            return;
        }
        try {
            String rfc = txtIngreseRFC.getText();
            Persona persona = rlb.VerificarPersona(rfc);
            if (persona != null) {
                txtNombre.setText(persona.getNombre() + " " + persona.getApellido_materno() + " " + persona.getApellido_paterno());
                Encriptador e = new Encriptador();
                String telefono = e.desencriptar(persona.getTelefono());
                txtTelefono.setText(telefono);

                Calendar fecha = persona.getFecha_nacimiento();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String fechaNacimiento = sdf.format(fecha.getTime());
                txtFecha_nacimiento.setText(fechaNacimiento);

                if (!datosMostrados) {
                    datosMostrados = true; // Marcar que los datos han sido mostrados
                    return; // Salir del método sin continuar hacia el cambio de ventana
                }
            } else {
                JOptionPane.showMessageDialog(null, "No hay ninguna persona con ese RFC.");
            }

            // Si se llega aquí, significa que los datos ya se han mostrado y se puede cambiar de ventana
            LicenciaDTO licencia = new LicenciaDTO();
            licencia.setPersona(rlb.VerificarPersona(txtIngreseRFC.getText()));
            ventana.cambiarVistaVigencia(licencia);
        } catch (persistenciaException ex) {
            Logger.getLogger(TramiteLicenciaMenu.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_BotonIngresarActionPerformed


    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        ventana.cambiarVistaMenu();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed

    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtIngreseRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngreseRFCActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtIngreseRFCActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtFecha_nacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecha_nacimientoActionPerformed

    }//GEN-LAST:event_txtFecha_nacimientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtFecha_nacimiento;
    private javax.swing.JTextField txtIngreseRFC;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
