/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Licencia;

import GUI.Ventana;

/**
 *
 * @author yohan
 */
public class TramiteLicenciaMenu extends javax.swing.JPanel {

    private Ventana ventana;

    /**
     * Creates new form Licencia
     */
    public TramiteLicenciaMenu() {
        initComponents();
    }
   public TramiteLicenciaMenu(Ventana ventana) {
        this.ventana = ventana;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIngreseRFC = new javax.swing.JTextField();
        txtIngreseRFC1 = new javax.swing.JTextField();
        txtIngreseRFC2 = new javax.swing.JTextField();
        txtIngreseRFC3 = new javax.swing.JTextField();
        BotonIngresar = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIngreseRFC.setBackground(new java.awt.Color(217, 217, 217));
        add(txtIngreseRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 240, 50));

        txtIngreseRFC1.setBackground(new java.awt.Color(217, 217, 217));
        add(txtIngreseRFC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 240, 50));

        txtIngreseRFC2.setBackground(new java.awt.Color(217, 217, 217));
        txtIngreseRFC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngreseRFC2ActionPerformed(evt);
            }
        });
        add(txtIngreseRFC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 250, 50));

        txtIngreseRFC3.setBackground(new java.awt.Color(217, 217, 217));
        add(txtIngreseRFC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 250, 50));

        BotonIngresar.setBorderPainted(false);
        BotonIngresar.setContentAreaFilled(false);
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 140, 30));

        BotonRegresar.setBorderPainted(false);
        BotonRegresar.setContentAreaFilled(false);
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });
        add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tramite 2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
ventana.cambiarVistaVigencia();
    }//GEN-LAST:event_BotonIngresarActionPerformed

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
ventana.cambiarVistaMenu();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void txtIngreseRFC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngreseRFC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngreseRFC2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtIngreseRFC;
    private javax.swing.JTextField txtIngreseRFC1;
    private javax.swing.JTextField txtIngreseRFC2;
    private javax.swing.JTextField txtIngreseRFC3;
    // End of variables declaration//GEN-END:variables
}
