/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Licencia;

import GUI.Ventana;

/**
 *
 * @author yohan
 */
public class VigenciaLicencia extends javax.swing.JPanel {

    private Ventana ventana;

    /**
     * Creates new form VigenciaLicencia1
     */
    public VigenciaLicencia() {
        initComponents();
    }
 public VigenciaLicencia(Ventana ventana) {
        this.ventana = ventana;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        BotonAceptar = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vigencia2.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(542, 346));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 350));

        BotonAceptar.setBorderPainted(false);
        BotonAceptar.setContentAreaFilled(false);
        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });
        add(BotonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 289, 140, 40));

        BotonRegresar.setBorderPainted(false);
        BotonRegresar.setContentAreaFilled(false);
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });
        add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 289, 144, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
ventana.cambiarVistaLicenciaGenerada();
    }//GEN-LAST:event_BotonAceptarActionPerformed

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
ventana.cambiarVistaLicencia();
    }//GEN-LAST:event_BotonRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
