/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Reportes;

import GUI.ControladorVentana;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Yohan Gabriel Melendrez Leal - 244907
 * @author Jesus Francisco Tapia Maldonado - 245136
 * @author Ximena Oliva Andrade - 247563
 */
public class ReportesGenerado extends javax.swing.JPanel {

    Connection conexionReporte;
    ReportesGenerado reporte1;
    ControladorVentana ventana;

    /**
     * Creates new form Reportes
     */
    public ReportesGenerado(ControladorVentana ventana) {
        this.ventana = ventana;
        this.reporte1 = new ReportesGenerado();
        initComponents();
    }

    public ReportesGenerado() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonRegresarMenu = new javax.swing.JButton();
        botonImprimir = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReporteExitosoCap.PNG"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        botonRegresarMenu.setToolTipText("");
        botonRegresarMenu.setBorderPainted(false);
        botonRegresarMenu.setContentAreaFilled(false);
        botonRegresarMenu.setFocusPainted(false);
        botonRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarMenuActionPerformed(evt);
            }
        });
        add(botonRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 230, 30));

        botonImprimir.setBorderPainted(false);
        botonImprimir.setContentAreaFilled(false);
        botonImprimir.setFocusPainted(false);
        botonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImprimirActionPerformed(evt);
            }
        });
        add(botonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 230, 20));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método para generar un informe utilizando JasperReports. Este método
     * establece una conexión con la base de datos y carga el archivo de informe
     * (.jasper) desde el directorio de recursos. Luego, utiliza JasperReports
     * para llenar el informe con los datos de la base de datos y devuelve el
     * objeto JasperPrint que representa el informe generado.
     *
     * @return El objeto JasperPrint que representa el informe generado.
     * @throws SQLException Si ocurre un error durante la conexión con la base
     * de datos.
     * @throws JRException Si ocurre un error durante la generación del informe
     * con JasperReports.
     * @throws FileNotFoundException Si no se encuentra el archivo de informe.
     */
    public JasperPrint reporteGenerado() throws SQLException, JRException, FileNotFoundException {
        conexionReporte = DriverManager.getConnection("jdbc:mysql://localhost:3306/Agencia", "root", "23300515");
        File reporte = new File(getClass().getResource("/reportes/ReporteAF.jasper").getFile());
        if (!reporte.exists()) {
            return null;
        }
        try {
            InputStream is = new BufferedInputStream(new FileInputStream(reporte.getAbsoluteFile()));
            JasperReport jr = (JasperReport) JRLoader.loadObject(is);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conexionReporte);

            return jp;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ReportesGenerado.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    private void botonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImprimirActionPerformed
        JasperPrint jp;
        try {
            jp = reporte1.reporteGenerado();
            JasperViewer.viewReport(jp);
        } catch (SQLException ex) {
            Logger.getLogger(ReportesGenerado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(ReportesGenerado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ReportesGenerado.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botonImprimirActionPerformed

    private void botonRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarMenuActionPerformed
        // TODO add your handling code here:
        ventana.cambiarVistaMenu();
    }//GEN-LAST:event_botonRegresarMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonImprimir;
    private javax.swing.JButton botonRegresarMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
