/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Reportes;

/**
 *
 * @author Ximena
 */
public class ReporteSolicitado extends javax.swing.JPanel {

    /**
     * Creates new form ReporteSolicitado
     */
    public ReporteSolicitado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCosto = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTipoTramite = new javax.swing.JTextField();
        txtFechaTramite = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCosto.setBackground(new java.awt.Color(217, 217, 217));
        add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 160, 40));

        txtNombre.setBackground(new java.awt.Color(217, 217, 217));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 160, 40));

        txtTipoTramite.setBackground(new java.awt.Color(217, 217, 217));
        add(txtTipoTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 160, 40));

        txtFechaTramite.setBackground(new java.awt.Color(217, 217, 217));
        add(txtFechaTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReportesGeneradosCap.PNG"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        botonAceptar.setText("jButton1");
        add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 140, 40));

        botonCancelar.setText("jButton1");
        add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 130, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtFechaTramite;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTipoTramite;
    // End of variables declaration//GEN-END:variables
}
