/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Reportes;

/**
 *
 * @author Ximena
 */
public class TramiteReporte extends javax.swing.JPanel {

    /**
     * Creates new form ReporteGenerado
     */
    public TramiteReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCurp = new javax.swing.JTextField();
        comboBoxTipoTramite = new javax.swing.JComboBox<>();
        datePickerPeriodo2 = new com.github.lgooddatepicker.components.DatePicker();
        datePickerPeriodo1 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel1 = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCurp.setText("jTextField1");
        txtCurp.setBackground(new java.awt.Color(217, 217, 217));
        txtCurp.setForeground(new java.awt.Color(217, 217, 217));
        add(txtCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 240, 40));

        comboBoxTipoTramite.setBackground(new java.awt.Color(217, 217, 217));
        comboBoxTipoTramite.setForeground(new java.awt.Color(217, 217, 217));
        comboBoxTipoTramite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboBoxTipoTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 240, 40));
        add(datePickerPeriodo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 190, -1));
        add(datePickerPeriodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 166, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TramiteReportesCap.PNG"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 130, 30));

        botonAceptar.setText("jButton1");
        add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 130, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JComboBox<String> comboBoxTipoTramite;
    private com.github.lgooddatepicker.components.DatePicker datePickerPeriodo1;
    private com.github.lgooddatepicker.components.DatePicker datePickerPeriodo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtCurp;
    // End of variables declaration//GEN-END:variables
}
