/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Reportes;

import GUI.ControladorVentana;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Yohan Gabriel Melendrez Leal - 244907
 * @author Jesus Francisco Tapia Maldonado - 245136
 * @author Ximena Oliva Andrade - 247563
 */
public class TramiteReporte extends javax.swing.JPanel {

    ControladorVentana ventana;

    /**
     * Creates new form ReporteGenerado
     */
    public TramiteReporte(ControladorVentana ventana) {
        this.ventana = ventana;
        initComponents();
    }

    /**
     * Creates new form HistorialGenerado
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datePickerPeriodo2 = new com.github.lgooddatepicker.components.DatePicker();
        datePickerPeriodo1 = new com.github.lgooddatepicker.components.DatePicker();
        comboBoxTipoTramite = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        botonRegresar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(datePickerPeriodo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 190, -1));
        add(datePickerPeriodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 166, 190, -1));

        comboBoxTipoTramite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licencia", "Placa" }));
        comboBoxTipoTramite.setBackground(new java.awt.Color(217, 217, 217));
        comboBoxTipoTramite.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxTipoTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoTramiteActionPerformed(evt);
            }
        });
        add(comboBoxTipoTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 240, 40));

        txtNombre.setBackground(new java.awt.Color(217, 217, 217));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 240, 40));

        botonRegresar.setBorderPainted(false);
        botonRegresar.setContentAreaFilled(false);
        botonRegresar.setDefaultCapable(false);
        botonRegresar.setFocusPainted(false);
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 130, 40));

        botonAceptar.setBorderPainted(false);
        botonAceptar.setContentAreaFilled(false);
        botonAceptar.setFocusPainted(false);
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        ventana.cambiarVistaMenu();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        try {

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date desde1 = sdf.parse(datePickerPeriodo2.getText());
            Calendar desde = Calendar.getInstance();
            desde.setTime(desde1);
            Calendar hasta = Calendar.getInstance();
            Date hasta2 = sdf.parse(datePickerPeriodo2.getText());
            hasta.setTime(hasta2);
            ventana.cambiarVistaReporteSolicitado(txtNombre.getText(), comboBoxTipoTramite.getSelectedItem().toString(), desde, hasta);

        } catch (Exception e) {
            ventana.cambiarVistaReporteSolicitado(txtNombre.getText(), comboBoxTipoTramite.getSelectedItem().toString(), null, null);
        }


    }//GEN-LAST:event_botonAceptarActionPerformed

    private void comboBoxTipoTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoTramiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTipoTramiteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JComboBox<String> comboBoxTipoTramite;
    private com.github.lgooddatepicker.components.DatePicker datePickerPeriodo1;
    private com.github.lgooddatepicker.components.DatePicker datePickerPeriodo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
