/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Consultas;

import Excepciones.persistenciaException;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ximena
 */
public class HistorialGenerado extends javax.swing.JPanel {

    /**
     * Creates new form HistorialGenerado
     */
    public HistorialGenerado() {
        initComponents();
    }
 public void tabla() throws persistenciaException {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id Activista");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido P");
        modelo.addColumn("Apellido M");
        modelo.addColumn("Telefono ");
        modelo.addColumn("FechaInicio ");

        String[] datos = new String[6];
        activistaDAO activista = new activistaDAO(conexionBD);
        try {
            List<> activistas = activista.consultarActivista();
            if (!activista.consultarActivista().isEmpty()) {
                for (int i = 0; i < activista.consultarActivista().size(); i++) {
                    datos[0] = Integer.toString(activistas.get(i).getId());
                    datos[1] = activistas.get(i).getNombre();
                    datos[2] = activistas.get(i).getApellidoPaterno();
                    datos[3] = activistas.get(i).getApellidoMaterno();
                    datos[4] = activistas.get(i).getTelefono();
                    datos[5] = activistas.get(i).getFechaInicio();
                    modelo.addRow(datos);
                }
                tablaSql.setModel(modelo);
            }
        } catch (persistenciaException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSql = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botonRegresarMenu = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaSql.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Activista", "Nombre", "Apellido P", "Apellido M", "Telefono", "FechaInicio"
            }
        ));
        jScrollPane2.setViewportView(tablaSql);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 530, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HistorialGeneradoCap.PNG"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        botonRegresarMenu.setText("jButton1");
        add(botonRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 230, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaSql;
    // End of variables declaration//GEN-END:variables
}
